######################## default configuration ####################
baseURL = "https://saleyell.netlify.app/"
#baseURL = "/"
languageCode = "ja-jp"
title = "SALE YELL"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""
canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "SALE YELLとは"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "ブログ"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "問合せ"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "SALE YELLとは"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "ブログ"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "SALE YELL"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = ""
email = ""
location = "Tokyo, Japan"
# copyright
copyright = "| copyright &copy; 2020 [SALE YELL](https://twitter.com/SaleYell) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/SaleYell"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

############################# markup########################
[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = true
        startLevel = 2
